name: sintonize
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo-sintoniza.png
    - assets/logo-musica.jpg
    - assets/notas-musicais.png
  fonts:
    - family: Offside
      fonts:
        - asset: assets/fonts/Offside-Regular.ttf
